### PR TITLE
Turn off screenshots for bespoke projects

### PR DESCRIPTION
**Pull request by yurivictor**
Screenshots don't work for bespoke projects. Not sure if this is something that is ever really a need, but this turns them off for now to stop errors from piling up.

### CODE REVIEW

**Comment by ryanmark** [comment]
Screenshots don't work for `app` projects. They should work for bespoke graphics projects.

**Comment by ryanmark** [comment]
Also they only don't work for us because of the proprietary integration with our CMS, they may be useful for other users of the open source project.

**Comment by ryanmark** [comment]
This instead should be handled by a flag in the deployer class.

**Comment by yurivictor** [comment]
Adds `screenshot` flag that defaults to true but allows users to overwrite in their own deploy.

For example:

```
module Autotune
  module Deployers
    class MyDeployer < Autotune::Deployer
      build_data['screenshot'] = true unless project.bespoke && project.type == 'app'
    end
  end
end
```

**Comment by ryanmark** [comment]
needs different approach

**Pull request closed without merging**
